leftnav:
- identifier: 7d81baa6-870f-6d77-68ee-34a72b7f8625
  name: Highlights of Calculus (5 videos)
  url: /pages/highlights_of_calculus
  weight: 10
- identifier: 1ed01475-c0bc-d266-84e1-9218f297165d
  name: Derivatives (12 videos)
  url: /pages/derivatives
  weight: 20
